###
//Create a new user (Farmer)
POST http://localhost:5000/api/v1/user
Content-Type: application/json

{
  "user_fullname": "Chye Zee Ching",
  "user_email": "chingc217@gmail.com",
  "user_password": "ching",
  "confirm_password": "ching",
  "user_role": "Admin",
  "user_phone": "0105650214"
}

###
//Create a new user (Farmer)
POST http://localhost:5000/api/v1/user
Content-Type: application/json

{
  "user_fullname": "Vincci Chye",
  "user_email": "vincci@gmail.com",
  "user_password": "vincci",
  "confirm_password": "vincci",
  "user_role": "Farmer",
  "user_phone": "0149420214"
}

###
//Create a new user (Worker)
POST http://localhost:5000/api/v1/user
Content-Type: application/json

{
  "user_fullname": "Ahmad",
  "user_email": "ahmad@gmail.com",
  "user_password": "ahmad",
  "confirm_password": "ahmad",
  "user_role": "Worker",
  "user_phone": "0149420214"
}

###
//Get All Users
GET http://localhost:5000/api/v1/user


###
//Get User by ID
GET http://localhost:5000/api/v1/user/0741f2b2-849f-456e-b3bd-5be2870971a4


###
//Update user (Admin)
PATCH http://localhost:5000/api/v1/user/80aa3040-7c54-4f38-9950-8c34927326e2
Content-Type: application/json

{
  "user_fullname": "Chye Zee Ching",
  "user_email": "chingc217@gmail.com",
  "user_password": "",
  "user_confirmPassword": "",
  "user_role": "Admin",
  "user_phone": "0105650214"
}


###
//delete user
DELETE http://localhost:5000/api/v1/user/0741f2b2-849f-456e-b3bd-5be2870971a4


###
//Login user (Admin)
POST http://localhost:5000/login
Content-Type: application/json

{
  "user_email": "chingc217@gmail.com",
  "user_password": "ching"
}

###
//Login user (Farmer)
POST http://localhost:5000/login
Content-Type: application/json

{
  "user_email": "vincci@gmail.com",
  "user_password": "vincci"
}

###
//Login user (Worker)
POST http://localhost:5000/login
Content-Type: application/json

{
  "user_email": "ahmad@gmail.com",
  "user_password": "ahmad"
}

###
GET http://localhost:5000/me

###
//Logout
DELETE http://localhost:5000/logout

###
//Get All CropList
GET http://localhost:5000/api/v1/crop

###
//Get Crop by id
GET http://localhost:5000/api/v1/crop/1ce30712-d26d-4d9c-9bcd-df833c6e6dc6


###
//Create CropList
POST http://localhost:5000/api/v1/crop
Content-Type: application/json

{
  "crop_name": "Lettuce"
}