###
//Create a new user (Farmer)
POST http://localhost:5000/api/v1/user
Content-Type: application/json

{
  "user_fullname": "Chye Zee Ching",
  "user_email": "chingc217@gmail.com",
  "user_password": "ching",
  "confirm_password": "ching",
  "user_role": "Admin",
  "user_phone": "0105650214"
}

###
//Create a new user (Farmer)
POST http://localhost:5000/api/v1/user
Content-Type: application/json

{
  "user_fullname": "Vincci Chye",
  "user_email": "vincci@gmail.com",
  "user_password": "vincci",
  "confirm_password": "vincci",
  "user_role": "Farmer",
  "user_phone": "0149420214"
}

###
//Create a new user (Worker)
POST http://localhost:5000/api/v1/user
Content-Type: application/json

{
  "user_fullname": "Ahmad",
  "user_email": "ahmad@gmail.com",
  "user_password": "ahmad",
  "confirm_password": "ahmad",
  "user_role": "Worker",
  "user_phone": "0149420214"
}

###
//Get All Users
GET http://localhost:5000/api/v1/user


###
//Get User by ID
GET http://localhost:5000/api/v1/user/0741f2b2-849f-456e-b3bd-5be2870971a4


###
//Update user (Admin)
PATCH http://localhost:5000/api/v1/user/80aa3040-7c54-4f38-9950-8c34927326e2
Content-Type: application/json

{
  "user_fullname": "Chye Zee Ching",
  "user_email": "chingc217@gmail.com",
  "user_password": "",
  "user_confirmPassword": "",
  "user_role": "Admin",
  "user_phone": "0105650214"
}


###
//delete user
DELETE http://localhost:5000/api/v1/user/0741f2b2-849f-456e-b3bd-5be2870971a4


###
//Login user (Admin)
POST http://localhost:5000/login
Content-Type: application/json

{
  "user_email": "chingc217@gmail.com",
  "user_password": "ching"
}

###
//Login user (Farmer)
POST http://localhost:5000/login
Content-Type: application/json

{
  "user_email": "vincci@gmail.com",
  "user_password": "vincci"
}

###
//Login user (Worker)
POST http://localhost:5000/login
Content-Type: application/json

{
  "user_email": "ahmad@gmail.com",
  "user_password": "ahmad"
}

###
GET http://localhost:5000/me

###
//Logout
DELETE http://localhost:5000/logout

###
//Get All CropList
GET http://localhost:5000/api/v1/crop

###
//Get Crop by id
GET http://localhost:5000/api/v1/crop/8994097e-efa5-4130-9c98-5dcc9745151c


###
//Create CropList
POST http://localhost:5000/api/v1/crop
Content-Type: application/json

{
  "crop_name": "Radish",
  "crop_active": 0
}

###
//Update CropList
PATCH http://localhost:5000/api/v1/crop/88d518b3-b53e-4d3a-9109-345dbebe76ca
Content-Type: application/json

{
  "crop_name": "Cucumber",
  "crop_active": 1
}


###
//Delete CropList
DELETE http://localhost:5000/api/v1/crop/1ce30712-d26d-4d9c-9bcd-df833c6e6dc6

###
//Get All Farming
GET http://localhost:5000/api/v1/farming

###
//Create FarmingList
POST http://localhost:5000/api/v1/farming
Content-Type: application/json

{
  "farming_name": "Fertilizer",
  "farming_date": "2023-05-14",
  "cropId": "1"
}

###
//Create Crop Management Record
POST http://localhost:5000/api/v1/cropManagement
Content-Type: application/json

{
  "c_management_date": "2023-05-11",
  "c_management_harvest": "120",
  "c_management_stored": "20",
  "c_management_sold": "100",
  "c_management_price": "11",
  "cropId": "1"
}

###
//Get Crop Management Record
GET http://localhost:5000/api/v1/cropManagement

###
//Get Crop Management Record by id
GET http://localhost:5000/api/v1/cropManagement/c38771b7-c077-4317-8f98-b80b0e5a34e3

###
//Create Crop Management Record
PATCH http://localhost:5000/api/v1/cropManagement/c38771b7-c077-4317-8f98-b80b0e5a34e3
Content-Type: application/json

{
  "c_management_date": "2023-05-11",
  "c_management_harvest": "120",
  "c_management_stored": "20",
  "c_management_sold": "100",
  "c_management_price": "10",
  "cropId": "1"
}

###
//Delete Crop Management Record
DELETE http://localhost:5000/api/v1/cropManagement/065a5838-079b-45eb-9b5d-5a9c6eeab1cb


###
//Get Weather
GET http://localhost:5000/api/v1/currentWeather

###
//Get Sensor
GET http://localhost:5000/api/v1/sensorData

###
//Get Sensor
GET http://localhost:5000/api/v1/sensorDataRealTime

###
//Create Sensor
POST http://localhost:5000/api/v1/sensorData